'use client'
import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { usePro, Practice } from '@/components/pro/ProWorkspace'
import { PROFESSIONS } from '@/lib/pro-finance'
const blank: Practice = { profession: '', practice_name: '', registration_number: '', address: '', contact_email: '', phone: '' }
export default function PracticePage() {
  const { request, reloadPractice } = usePro()
  const [form, setForm] = useState<Practice>(blank), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  useEffect(() => { request('/api/pro/practice').then(r => setForm({ ...blank, ...r.practice })).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [request])
  async function save(e: FormEvent) { e.preventDefault(); setSaving(true); setError(''); setNotice(''); try { await request('/api/pro/practice', { method: 'PUT', body: JSON.stringify(form) }); await reloadPractice(); setNotice('Les informations de votre cabinet sont enregistrées.') } catch (e) { setError(e instanceof Error ? e.message : 'Enregistrement impossible.') } finally { setSaving(false) } }
  return <><div className="cp-heading"><div><p className="cp-kicker">MON ACTIVITÉ</p><h1>Mon cabinet</h1><p>Un espace adapté à votre profession, du soin à l’accompagnement.</p></div><Link className="cp-button secondary" href="/pro/parametres">Profil public et paramètres</Link></div>{error && <div role="alert" className="cp-notice error">{error}</div>}{notice && <div role="status" className="cp-notice">{notice}</div>}<div className="cp-grid"><form onSubmit={save} className="cp-card"><div className="cp-card-head"><div><h2>Identité professionnelle</h2><p>Ces coordonnées apparaissent sur vos bilans d’activité.</p></div></div><div className="cp-form-grid"><label className="cp-field full">Profession / catégorie de praticien<input required list="professions" maxLength={120} value={form.profession} onChange={e => setForm({ ...form, profession: e.target.value })} placeholder="Votre profession"/><datalist id="professions">{PROFESSIONS.map(p => <option key={p} value={p}/>)}</datalist><small>Choisissez une profession ou saisissez la vôtre.</small></label>{([['practice_name', 'Nom du cabinet / nom professionnel', 180], ['registration_number', 'Identifiant professionnel ou entreprise', 100], ['contact_email', 'E-mail professionnel', 254], ['phone', 'Téléphone', 50]] as const).map(([key, label, max]) => <label className="cp-field" key={key}>{label}<input type={key === 'contact_email' ? 'email' : 'text'} required={key === 'practice_name'} maxLength={max} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>)}<label className="cp-field full">Adresse professionnelle<textarea maxLength={500} value={form.address} onChange={e => setForm({ ...form, address: e.target.value })}/></label></div><button disabled={loading || saving} className="cp-button" style={{ marginTop: 22 }}>{saving ? 'Enregistrement…' : 'Enregistrer mon cabinet'}</button></form><div className="cp-stack"><section className="cp-banner"><p className="cp-kicker">CHAQUE PRATIQUE A SA PLACE</p><h2>Du temps pour votre métier.</h2><p>Quelle que soit votre pratique, Les outils de gestion restent communs, votre profession vous distingue.</p></section><section className="cp-card"><h2>Vos informations privées</h2><p className="cp-note">Les coordonnées du cabinet et les données comptables sont privées. Votre présentation publique et votre spécialité visible se gèrent séparément dans les paramètres du profil.</p><Link href="/pro/parametres" className="cp-button secondary">Gérer mon profil public</Link></section></div></div></>
}
